apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-optimization-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-optimization
  template:
    metadata:
      labels:
        app: inventory-optimization
    spec:
      containers:
      - name: inventory-optimization
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi 