apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasage-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datasage
  template:
    metadata:
      labels:
        app: datasage
    spec:
      containers:
      - name: inventory-optimization
        image: us-central1-docker.pkg.dev/inventory-optimization-444419/datasage/datasage:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi 